### ISSUE TITLE
Newline characters in coin notes breaks import functionality

### ISSUE THREAD

**Issue by anwilli5** [anwilli5/coin-collection-android-US#10]
Newline characters cause empty lines (or lines with unexpected formatting) to be produced in the exported .csv files, which causes parsing errors upon import.  Sounds like we need to escape new line characters as well?

**Comment by anwilli5** [comment]
Actually, let's just base64 encode the notes so that weird characters aren't a problem anymore

**Comment by sw23** [comment]
Why not just switch to a format like json for the saved data?
