### ISSUE TITLE
Add button to insert custom coin

### ISSUE THREAD

**Issue by Mahki-S** [anwilli5/coin-collection-android-US#76]
### 💭 Description

Certain coins (such as the Kennedys) have variants that aren't on the application. I don't know how extensively this occurs, so I thought that maybe being able to add an entirely new coin with a title to a section would be a good solution. A 1976 S is in your collection but not native? Add it yourself! I can't code to save my soul so I imagine it's not as simple as that, but I thought it might help with expanding into more niche variants that wouldn't be as common.

I think a PC variant would be a grand idea also. I don't know the logistics of it, but if I had a nickel for every time I wanted to use this app on the PC, I wouldn't need to collect anymore.

Also, this is by far the best coin collecting application out there. I mean that: I've gone through a couple dozen and they all have issues ranging from a horrendous interface to customization issues. Great work!

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/anwilli5/coin-collection-android-US/blob/2d51333dd08c40c3fbc6a6897948209e1a6210c6/CODE_OF_CONDUCT.md)

**Comment by sw23** [comment]
If your PC is running Windows then you should be able to run the app on there at some point. I read that they are working on that feature, where you can download apps from the Amazon Appstore on Windows. I haven't tried it, but will give it a try at some point. It looks like currently it requires a few steps but I suspect it will become easier as they work on it more

**Comment by sw23** [comment]
I've added a button so that you can now add a custom custom (instead of having to copy/modify an existing coin). I'll open a separate issue for getting this to work on Windows. I haven't explored that in a while.
