### ISSUE TITLE
Availability outside Play Store?

### ISSUE THREAD

**Issue by IzzySoft** [anwilli5/coin-collection-android-US#78]
### 💭 Description

Are there plans to make the app available outside the walled garden of Google Play – for those having no access there (e.g. no Google account, no Play Services on their devices – be it for privacy reasons or because the device vendor didn't ship it)? You could e.g. attach the APK file to your tags/releases, as it's wide-spread use.

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/anwilli5/coin-collection-android-US/blob/2d51333dd08c40c3fbc6a6897948209e1a6210c6/CODE_OF_CONDUCT.md)

**Comment by sw23** [comment]
I personally hadn't really thought about it, but seems like a reasonable idea. We've had people ask for older versions of the app before, so might be a useful way to provide those as well.

**Comment by IzzySoft** [comment]
Where people of the mentioned group would look first is your [`releases/`](https://github.com/anwilli5/coin-collection-android-US/releases) – you currently haven't tagged any, so you could preferably consider that as well. The most common pattern for tag names is prefixing the `versionName` with a `v`, e.g. `v3.3.1` for your current `versionName: "3.3.1"` (though something like `c27` if you want to co by `versionCode` would work fine as well).

If you'd let me know once it's available, I probably could include it with [my repo](https://apt.izzysoft.de/fdroid), which is quite popular with … you guess it :rofl: Updates would then be pulled automatically within 24h of your making them available, and users get notified via their favourite [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181). If you wish you could then even go one step further and apply for inclusion with the [F-Droid.org](https://f-droid.org/) repository.

**Comment by sw23** [comment]
Thanks for the detailed info! I'll let you know when this gets set up

**Comment by sw23** [comment]
@IzzySoft I've created a release matching the current app version here:
https://github.com/anwilli5/coin-collection-android-US/releases/tag/v3.3.1

I've been researching and will likely set up a Github Action to generate the releases, but will make them manually until I get that set up. Note that there are two APKs which are the same other than the package name: 'android' which goes to Google Play store and 'amazon' which goes to the Amazon Appstore. You'd probably want the 'android' one

**Comment by IzzySoft** [comment]
Thanks a lot! I've just added your app to my repo: it will [become available here](https://apt.izzysoft.de/fdroid/index/apk/com.spencerpages) at around 19:00 UTC today. So if you wish, you can add [a third badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to your row on the Readme then :smiley:

And yes, I guess the 'android' one will be the right one, so I've picked that. Updates are fetched automatically within 24h of your tagging them (and attaching the APKs of course) – ah, I've already mentioned that :rofl:
