### ISSUE TITLE
Create Github 'Feature Request' issue template

### ISSUE THREAD

**Issue by sw23** [anwilli5/coin-collection-android-US#86]
Last year for Hacktoberfest @Yashesvinee was nice enough to [add an issue template for bug reports](https://github.com/anwilli5/coin-collection-android-US/pull/59). Thanks, Yashesvinee!

That one works great for bugs, but we need one for new feature requests as well. The fields in the bug template don't really make sense for new features, and we'd want to differentiate them with different labels.

More details about Github issue templates:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

**Comment by ManasviGoyal** [comment]
I would like to work on this

**Comment by sw23** [comment]
@ManasviGoyal Sweet, thanks! All yours : )

**Comment by ManasviGoyal** [comment]
Done. @sw23 please check
